version: 0.2
    
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore 
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build 
      - echo Test started on `date`
      - dotnet test 
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Debug
      - zip -j ./package.zip ./DotNetCoreLambda/bin/Debug/netcoreapp2.1/publish/*
      - aws s3 cp package.zip s3://chetan1123/lambda/${CODEBUILD_BUILD_NUMBER}/
      - aws cloudformation update-stack --stack-name lambda-demo --use-previous-template --capabilities CAPABILITY_IAM --parameters  ParameterKey=BUILDNUMBER,ParameterValue=${CODEBUILD_BUILD_NUMBER}
      
artifacts:
  files:
    - ./**/*
