version: 0.2
    
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore 
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build 
      - echo Test started on `date`
      - dotnet test 
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release
      - zip -j ./package.zip ./DotNetCoreLambda/bin/Release/netcoreapp2.1/publish/*
      - aws s3 cp package.zip s3://chetan1123
      
artifacts:
  files:
    - ./**/*
